---

- file: path=~/.i3 state=directory
- file: path=~/.bin state=directory

- blockinfile:
    block="{{ lookup('template', 'templates/.bashrc') }}"
    dest=~/.bashrc

- template: src=templates/dotnet.sh dest=/etc/profile.d
  become: yes

- template: src=templates/slick-greeter.conf dest=/etc/lightdm/slick-greeter.conf
  become: yes
  
- template: src=templates/.i3/config dest=~/.i3/
- synchronize: src=templates/.i3/vol.sh dest=~/.i3/
- template: src=templates/alacritty.yml dest=~/.config/alacritty/
- template: src=templates/fonts.conf dest=~/.config/fontconfig/
- template: src=templates/starship.toml dest=~/.config/
- synchronize: src=templates/.bin/ dest=~/.bin/
- template: src=templates/.bash_aliases dest=~/.bash_aliases
- template: src=templates/.gitconfig dest=~/.gitconfig
- template: src=templates/.tmux.conf dest=~/.tmux.conf
- template: src=templates/.Xresources dest=~/.Xresources
- template: src=templates/.vimrc dest=~/.vimrc
- synchronize: src=templates/dunst/ dest=~/.config/dunst/

- template: src=templates/rofi/config.rasi dest=~/.config/rofi/
- template: src=templates/rofi/style-gugu.rasi dest=~/.config/rofi/

- template: src=templates/.i3/config.toml dest=~/.i3/ force=no