
- name: Include vars of theme
  include_vars:
    file: theme/{{ theme }}.yml
    name: theme

- name: Apply dotfiles templates
  import_tasks: dotfiles.yml

- name: Install minimal tools
  import_tasks: minimal_tools.yml

- name: Install egpu
  import_tasks: egpu.yml
  when: egpu == true

- name: Install numlockx
  import_tasks: numlockx.yml