
- name: Enable AUR for pamac
  replace:
    path: /etc/pamac.conf
    regexp: '^#EnableAUR$'
    replace: 'EnableAUR'
  become: yes

- name: Enable AUR updates for pamac
  replace:
    path: /etc/pamac.conf
    regexp: '^#CheckAURUpdates$'
    replace: 'CheckAURUpdates'
  become: yes

- name: Remove unwanted tools ...
  shell: pamac remove --no-confirm urxvt urxvt-perls bash-git-prompt
  become: yes
  ignore_errors: yes

- name: Install minimal tools ...
  shell: pamac install --no-confirm tmux httpie jq alacritty noto-fonts-emoji
  become: yes

- name: Install minimal tools from AUR...
  shell: pamac build --no-confirm starship-bin

- name: Replace  minimal tools ...
  shell: rm /usr/bin/terminal && ln -s /usr/bin/alacritty /usr/bin/terminal
  become: yes
