
- name: Enable AUR for pamac
  replace:
    path: /etc/pamac.conf
    regexp: '^#EnableAUR$'
    replace: 'EnableAUR'
  become: yes

- name: Enable AUR updates for pamac
  replace:
    path: /etc/pamac.conf
    regexp: '^#CheckAURUpdates$'
    replace: 'CheckAURUpdates'
  become: yes

- name: Remove unwanted tools ...
  shell: |
    pamac remove --unneeded --no-confirm urxvt
    pamac remove --unneeded --no-confirm urxvt-perls
    pamac remove --unneeded --no-confirm bash-git-prompt
  become: yes
  ignore_errors: yes

- name: Install minimal tools ...
  shell: pamac install --no-confirm tmux httpie jq alacritty noto-fonts-emoji z starship rofi flameshot i3status-rust playerctl awesome-terminal-fonts ttf-font-awesome pamixer
  become: yes

- name: Replace minimal tools ...
  shell: rm -f /usr/bin/terminal && ln -s /usr/bin/alacritty /usr/bin/terminal
  become: yes
